import { listTodosFlow } from '@/common/model/fixtures';

/** Mappen i repot som appen bevakar, relativt repots rot. */
export const HIGHAI_DIR = '.highai';
export const FLOWS_DIR = `${HIGHAI_DIR}/flows`;
export const GUIDE_FILE = `${HIGHAI_DIR}/README.md`;

export function isFlowFile(name: string): boolean {
  return name.endsWith('.json') && !name.endsWith('.errors.json');
}

export function errorsFileFor(name: string): string {
  return name.replace(/\.json$/, '.errors.json');
}

/**
 * Guiden som AI-agenten i terminalen läser. Skrivs till `.highai/README.md`
 * i repot när det öppnas. Bumpa versionen när innehållet ändras så att
 * gamla kopior skrivs över.
 */
export const GUIDE_VERSION = 1;

export function buildGuide(): string {
  return `<!-- highai-guide v${GUIDE_VERSION}, generated by Highai, do not edit -->
# Highai: how to deliver a flow

Highai is a desktop app that draws animated sequence diagrams of data flows
through a codebase. It is running right now and watching this folder. The user
asks you, in the terminal, about a flow such as "what happens when a todo is
added?" or "what happens if the webhook call fails?". You answer by writing a
flow file. The user sees it in the app the moment you save it.

## Deliver

- Write one JSON object matching the schema below to \`${FLOWS_DIR}/<kebab-case-name>.json\`,
  relative to the repository root. Use a name that describes the flow, e.g. \`add-todo.json\`.
- Highai validates the file as soon as it is saved. If it is accepted the flow is shown
  and selected in the app. If it is rejected the reasons are written to
  \`${FLOWS_DIR}/<name>.errors.json\`. Read that file, fix the flow and save again.
- Saving a file with the same name again replaces the earlier flow. Use a new name for
  a different flow, for example a variant where something fails.
- Do not create other files in \`${HIGHAI_DIR}/\`. After saving, tell the user in one or two
  sentences what the flow shows.

## How to build a good flow

1. Start from the entry point the user's question implies: a UI action, an HTTP request,
   a queue message, a scheduled job. Read the code and follow the data through handlers,
   routes, services, storage, caches, queues and external systems, and back to the caller.
2. Everything that exists in this repository needs a \`source\`: a path relative to the
   repository root and a 1-based line number that really exists. Highai checks both.
   Point at the line where the function is declared (nodes) or where the call is made (edges).
   Nodes of kind \`db\`, \`cache\`, \`external\` and \`queue\` may omit \`source\`.
3. Group nodes into \`systems\`, one per deployable application or infrastructure component:
   the frontend, the API, Postgres, Redis, a webhook consumer. Highai shows the systems first
   and lets the user zoom into each one. Every system must have at least one node.
4. Describe tables on \`db\` and \`cache\` nodes with columns, primary keys and foreign keys
   (\`references\` may only point at tables on the same node). On every edge that touches
   storage, list the \`tables\` it reads or writes. Point \`source\` on a table at the
   migration or schema file that defines it.
5. Order \`steps\` the way the flow actually runs. Responses are edges of their own going
   back to the caller, e.g. "200 OK with the todo". Every step references an edge id.
6. Keep labels short and use the code's own names (component, function, route, table).
   Put detail in \`description\`, \`payload\` and \`response\`.
7. If the user asks about a failure or an alternative path, model that path: the edge that
   fails, what catches it, what is rolled back or retried, and what the caller sees.

## Schema

\`\`\`ts
interface Flow {
  question: string;   // the user's question
  title: string;      // short, e.g. "Add todo"
  summary: string;    // one or two sentences about what the flow does
  systems: System[];  // at least one
  nodes: Node[];      // at least one
  edges: Edge[];      // at least one
  steps: Step[];      // playback order, at least one
}

interface System {
  id: string;
  kind: 'app' | 'api' | 'db' | 'cache' | 'external' | 'queue';
  label: string;
  description?: string;
}

interface Node {
  id: string;
  kind: 'ui'        // something the user interacts with: button, form, page
      | 'handler'   // client code reacting to an event: handler, hook, action
      | 'http'      // HTTP endpoint or route in a backend
      | 'service'   // internal service, module or class in a backend
      | 'db'        // database or other storage
      | 'cache'     // Redis, in-memory cache, CDN
      | 'external'  // system outside the repository: payment provider, third-party API
      | 'queue';    // queue, topic or event bus
  system: string;     // System.id
  label: string;
  description?: string;
  source?: Source;    // required unless kind is db, cache, external or queue
  tables?: Table[];   // what the node stores, mainly for db and cache
}

interface Table {
  name: string;
  description?: string;
  columns?: Column[];
  source?: Source;    // where the schema is defined
}

interface Column {
  name: string;
  type: string;
  description?: string;
  primaryKey?: boolean;
  references?: { table: string; column: string }; // foreign key to a table on the same node
}

interface Edge {
  id: string;
  from: string;       // Node.id
  to: string;         // Node.id
  label: string;      // short, e.g. "POST /api/todos" or "INSERT todos"
  payload?: string;   // what is sent, free text or example JSON
  response?: string;  // what comes back, if anything
  source: Source;     // the line where the call is made
  tables?: string[];  // Table.name on the target node
}

interface Step {
  edgeId: string;     // Edge.id
  description: string; // one sentence about what happens in this step
}

interface Source {
  file: string;       // relative to the repository root
  line: number;       // 1-based, must exist in the file
  endLine?: number;
}
\`\`\`

Ids must be unique within their list. Every \`system\`, \`from\`, \`to\`, \`edgeId\` and
\`tables\` entry must reference something that exists.

## Example

A complete flow from a different repository, a small todo app with a React
frontend, an Express API, Postgres and Redis:

\`\`\`json
${JSON.stringify(listTodosFlow, null, 2)}
\`\`\`
`;
}
