import { listTodosFlow } from '@/common/model/fixtures';

/** Mappen i repot som appen bevakar, relativt repots rot. */
export const REVERIK_DIR = '.reverik';
export const FLOWS_DIR = `${REVERIK_DIR}/flows`;
export const REVIEWS_DIR = `${REVERIK_DIR}/reviews`;
export const GUIDE_FILE = `${REVERIK_DIR}/instructions.md`;

export function isFlowFile(name: string): boolean {
  return name.endsWith('.json') && !name.endsWith('.errors.json');
}

export function errorsFileFor(name: string): string {
  return name.replace(/\.json$/, '.errors.json');
}

/**
 * Guiden som AI-agenten i terminalen läser. Skrivs till `.reverik/instructions.md`
 * i repot när det öppnas. Bumpa versionen när innehållet ändras så att
 * gamla kopior skrivs över.
 */
export const GUIDE_VERSION = 6;

export function buildGuide(): string {
  return `<!-- reverik-guide v${GUIDE_VERSION}, generated by Reverik, do not edit -->
# Reverik: how to deliver a flow

Reverik is a desktop app that draws animated sequence diagrams of data flows
through a codebase. It is running right now and watching this folder. The user
asks you, in the terminal, about a flow such as "what happens when a todo is
added?" or "what happens if the webhook call fails?". You answer by writing a
flow file. The user sees it in the app the moment you save it.

**The flow file is the only deliverable.** Do not draw the flow yourself: no
artifacts, no HTML pages, no Mermaid, no ASCII diagrams, no long prose
walkthroughs. Reverik renders the diagram from the JSON. Answer questions about
the code normally, but whenever the user asks how something flows, works, or
fails, write the file.

## Deliver

- Write one JSON object matching the schema below to \`${FLOWS_DIR}/<kebab-case-name>.json\`,
  relative to the repository root. Use a name that describes the flow, e.g. \`add-todo.json\`.
- Reverik validates the file as soon as it is saved. If it is accepted the flow is shown
  and selected in the app. If it is rejected the reasons are written to
  \`${FLOWS_DIR}/<name>.errors.json\`. Read that file, fix the flow and save again.
- Saving a file with the same name again replaces the earlier flow. Use a new name for
  a different flow, for example a variant where something fails.
- Do not create other files in \`${REVERIK_DIR}/\`. After saving, tell the user in one or two
  sentences what the flow shows.
- A review of a change is delivered the same way, to \`${REVIEWS_DIR}/<name>.json\`. See
  "Reviews" below.

## How to build a good flow

1. Start from the entry point the user's question implies: a UI action, an HTTP request,
   a queue message, a scheduled job. Read the code and follow the data through handlers,
   routes, services, storage, caches, queues and external systems, and back to the caller.
2. Everything that exists in this repository needs a \`source\`: a path relative to the
   repository root and a 1-based line number that really exists. Reverik checks both.
   Point at the line where the function is declared (nodes) or where the call is made (edges).
   Nodes of kind \`db\`, \`cache\`, \`external\` and \`queue\` may omit \`source\`.
3. Group nodes into \`systems\`, one per deployable application or infrastructure component:
   the frontend, the API, Postgres, Redis, a webhook consumer. Reverik shows the systems first
   and lets the user zoom into each one. Every system must have at least one node.
4. Describe tables on \`db\` and \`cache\` nodes with columns, primary keys and foreign keys
   (\`references\` may only point at tables on the same node). On every edge that touches
   storage, list the \`tables\` it reads or writes. Point \`source\` on a table at the
   migration or schema file that defines it.
5. Order \`steps\` the way the flow actually runs. Responses are edges of their own going
   back to the caller, e.g. "200 OK with the todo". Every step references an edge id.
6. Keep labels short and use the code's own names (component, function, route, table).
   Put detail in \`description\`, \`payload\` and \`response\`.
7. If the user asks about a failure or an alternative path, model that path: the edge that
   fails, what catches it, what is rolled back or retried, and what the caller sees.

## Schema

\`\`\`ts
interface Flow {
  question: string;   // the user's question
  title: string;      // short, e.g. "Add todo"
  summary: string;    // one or two sentences about what the flow does
  systems: System[];  // at least one
  nodes: Node[];      // at least one
  edges: Edge[];      // at least one
  steps: Step[];      // playback order, at least one
}

interface System {
  id: string;
  kind: 'app' | 'api' | 'db' | 'cache' | 'external' | 'queue';
  label: string;
  description?: string;
}

interface Node {
  id: string;
  kind: 'ui'        // something the user interacts with: button, form, page
      | 'handler'   // client code reacting to an event: handler, hook, action
      | 'http'      // HTTP endpoint or route in a backend
      | 'service'   // internal service, module or class in a backend
      | 'db'        // database or other storage
      | 'cache'     // Redis, in-memory cache, CDN
      | 'external'  // system outside the repository: payment provider, third-party API
      | 'queue';    // queue, topic or event bus
  system: string;     // System.id
  label: string;
  description?: string;
  source?: Source;    // required unless kind is db, cache, external or queue
  tables?: Table[];   // what the node stores, mainly for db and cache
}

interface Table {
  name: string;
  description?: string;
  columns?: Column[];
  source?: Source;    // where the schema is defined
}

interface Column {
  name: string;
  type: string;
  description?: string;
  primaryKey?: boolean;
  references?: { table: string; column: string }; // foreign key to a table on the same node
}

interface Edge {
  id: string;
  from: string;       // Node.id
  to: string;         // Node.id
  label: string;      // short, e.g. "POST /api/todos" or "INSERT todos"
  payload?: string;   // what is sent, free text or example JSON
  response?: string;  // what comes back, if anything
  source: Source;     // the line where the call is made
  tables?: string[];  // Table.name on the target node
}

interface Step {
  edgeId: string;     // Edge.id
  description: string; // one sentence about what happens in this step
}

interface Source {
  file: string;       // relative to the repository root
  line: number;       // 1-based, must exist in the file
  endLine?: number;
}
\`\`\`

Ids must be unique within their list. Every \`system\`, \`from\`, \`to\`, \`edgeId\` and
\`tables\` entry must reference something that exists.

## Reviews

When the user asks you to review a change (a branch against another branch, a commit,
a diff), deliver one review file per affected data flow to \`${REVIEWS_DIR}/<name>.json\`:

\`\`\`ts
interface ReviewDocument {
  baseLabel: string;    // what the change is compared against, e.g. "main"
  headLabel: string;    // the change itself, e.g. "feature/todo-lists"
  base: Flow;           // the flow as it works on base, before the change
  head: Flow;           // the same flow as it works on head, after the change
  findings: Finding[];  // what looks wrong or risky, may be empty
}

interface Finding {
  id: string;
  severity: 'error' | 'warning' | 'info';
  title: string;        // short, e.g. "The cached list is no longer invalidated"
  description: string;  // what happens and why it matters
  suggestion?: string;  // what to do instead
  nodeId?: string;      // Node.id in head, or in base if the node was removed
  edgeId?: string;      // Edge.id in head, or in base if the call was removed
  source?: Source;      // file and line on head
}
\`\`\`

Rules for reviews:

- Read the diff first (\`git diff <base>...<head>\` and the changed files), then follow
  the flows the change touches. Ignore flows the change does not affect.
- Keep the same node and edge ids in \`base\` and \`head\` for things that are the same,
  so Reverik can show what was added, removed and changed. Give new things new ids.
- Use real git references as \`headLabel\` and \`baseLabel\`, e.g. \`feature/x\`,
  \`origin/feature/x\` or a commit. Reverik checks \`head\` sources against \`headLabel\`
  when it resolves in this repository (run \`git fetch\` first), so the branch does not
  need to be checked out. If it does not resolve, the working tree is used. \`base\` is
  not checked.
- Point every finding at a node or a call, and at a file and line where possible. Look
  for: cache invalidation that disappeared, calls that are now awaited or reordered,
  work moved inside or outside a transaction, missing error handling or validation,
  N+1 queries, secrets or data leaving the system, retries and timeouts.
- If nothing looks wrong, say so with an \`info\` finding rather than inventing problems.

## Example

A complete flow from a different repository, a small todo app with a React
frontend, an Express API, Postgres and Redis:

\`\`\`json
${JSON.stringify(listTodosFlow, null, 2)}
\`\`\`
`;
}
